# Generated by Django 5.1.6 on 2025-02-23 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(default=' ', upload_to='jobs/'),
            preserve_default=False,
        ),
    ]
