# Generated by Django 5.1.6 on 2025-02-26 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_alter_job_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=500)),
                ('website', models.URLField(max_length=500)),
                ('cv', models.FileField(upload_to='job/files')),
                ('coverliter', models.TextField()),
            ],
        ),
    ]
